"""Tests for Phase 5C — CertificateLifecycleService, PKI routes."""
from __future__ import annotations

import pytest


class TestCertificateLifecycleServiceImports:
    def test_imports(self):
        from recon_api.services.certificate_lifecycle import (
            CertificateLifecycleService,
        )
        assert CertificateLifecycleService is not None

    def test_no_bare_except(self):
        import inspect
        from recon_api.services import certificate_lifecycle
        src = inspect.getsource(certificate_lifecycle)
        for i, line in enumerate(src.split("\n"), 1):
            if line.strip() == "except:" or line.strip() == "except :":
                pytest.fail(f"Bare except at line {i}")

    def test_required_methods_present(self):
        from recon_api.services.certificate_lifecycle import (
            CertificateLifecycleService,
        )
        methods = [m for m in dir(CertificateLifecycleService)
                   if not m.startswith("_")]
        required = [
            "submit_csr", "approve_csr", "reject_csr",
            "revoke_certificate", "is_revoked", "get_revocation_list",
            "get_renewal_queue", "renew_collector_cert",
        ]
        missing = [m for m in required if m not in methods]
        assert not missing, f"Missing methods: {missing}"


class TestCSRValidation:
    def test_invalid_csr_pem_raises_error(self):
        """Garbage PEM should raise ValueError."""
        from recon_api.services.certificate_lifecycle import (
            CertificateLifecycleService,
        )
        # We can't call async methods directly, but we can test the
        # underlying validation by attempting to parse
        from cryptography import x509
        from cryptography.hazmat.backends import default_backend
        with pytest.raises((ValueError, Exception)):
            x509.load_pem_x509_csr(b"not-a-csr", default_backend())

    def test_valid_csr_pem_parses(self):
        """Real CSR generated by cryptography library should parse."""
        from cryptography.hazmat.primitives.asymmetric import rsa
        from cryptography.hazmat.primitives import hashes, serialization
        from cryptography import x509
        from cryptography.x509.oid import NameOID
        from cryptography.hazmat.backends import default_backend

        key = rsa.generate_private_key(65537, 2048, default_backend())
        csr = (
            x509.CertificateSigningRequestBuilder()
            .subject_name(x509.Name([
                x509.NameAttribute(NameOID.COMMON_NAME, "collector_test"),
            ]))
            .sign(key, hashes.SHA256(), default_backend())
        )
        csr_pem = csr.public_bytes(serialization.Encoding.PEM)
        parsed = x509.load_pem_x509_csr(csr_pem, default_backend())
        cn = parsed.subject.get_attributes_for_oid(NameOID.COMMON_NAME)
        assert cn[0].value == "collector_test"

    def test_invalid_purpose_value(self):
        from recon_api.services.certificate_lifecycle import VALID_PURPOSES
        assert "collector" in VALID_PURPOSES
        assert "report_viewer" in VALID_PURPOSES
        assert "report_signing" in VALID_PURPOSES
        assert "invalid" not in VALID_PURPOSES


class TestRenewalQueueStructure:
    def test_structure_constants(self):
        """Verify renewal queue method exists with expected return keys."""
        import inspect
        from recon_api.services.certificate_lifecycle import (
            CertificateLifecycleService,
        )
        src = inspect.getsource(CertificateLifecycleService.get_renewal_queue)
        assert "expired" in src
        assert "critical" in src
        assert "warning" in src
        assert "total" in src


class TestCertificateServiceExtension:
    def test_load_project_ca_method_exists(self):
        from recon_api.services.certificate import CertificateService
        assert hasattr(CertificateService, "load_project_ca")

    def test_load_project_ca_is_static(self):
        import inspect
        from recon_api.services.certificate import CertificateService
        method = getattr(CertificateService, "load_project_ca")
        assert isinstance(
            inspect.getattr_static(CertificateService, "load_project_ca"),
            staticmethod,
        )


class TestPurposeValidityDays:
    def test_validity_days_defined(self):
        from recon_api.services.certificate_lifecycle import PURPOSE_VALIDITY_DAYS
        assert PURPOSE_VALIDITY_DAYS["collector"] == 30
        assert PURPOSE_VALIDITY_DAYS["report_viewer"] == 90
        assert PURPOSE_VALIDITY_DAYS["report_signing"] == 730


# ── Route tests ───────────────────────────────────────────────

class TestCertificateRoutes:
    async def test_csr_list_requires_auth(self, async_client):
        r = await async_client.get("/api/v1/certificates/fake-id/csrs/")
        assert r.status_code in (401, 403)

    async def test_revocation_list_requires_auth(self, async_client):
        r = await async_client.get(
            "/api/v1/certificates/fake-id/revocation-list/"
        )
        assert r.status_code in (401, 403)

    async def test_renewal_queue_requires_auth(self, async_client):
        r = await async_client.get(
            "/api/v1/certificates/fake-id/renewal-queue/"
        )
        assert r.status_code in (401, 403)

    async def test_submit_csr_requires_auth(self, async_client):
        r = await async_client.post(
            "/api/v1/certificates/fake-id/csrs/",
            json={
                "csr_pem": "-----BEGIN CERTIFICATE REQUEST-----\nfake",
                "requested_purpose": "collector",
            },
        )
        assert r.status_code in (401, 403)

    async def test_revoke_requires_auth(self, async_client):
        r = await async_client.post(
            "/api/v1/certificates/fake-id/revoke/",
            json={"serial_number": "ABC123"},
        )
        assert r.status_code in (401, 403)

    async def test_approve_requires_auth(self, async_client):
        r = await async_client.post(
            "/api/v1/certificates/fake-id/csrs/fake-csr/approve/"
        )
        assert r.status_code in (401, 403)
